### ISSUE TITLE
Bug: Consecutive Diffs (diff not visible in the frontend)

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix-svelte-frontend#252]
I've attached a database and two resources (only the resource `business-service-providers.json` is important).

When I compare revision 1 and 2 I should get a diff, but the frontend doesn't show this diff.

```
localhost/json-db/business-service-providers.json (JSON)> diff -s 1 -e 2
[
  {
    "insert": {
      "nodeKey": 188,
      "insertPositionNodeKey": 86,
      "insertPosition": "asRightSibling",
      "deweyID": "1.17.113.0.17.0.17.0.49.0.97",
      "depth": 6,
      "type": "jsonFragment",
      "data": "{\"name\":\"keyword\"}"
    }
  }
]
```

[json-db.zip](https://github.com/sirixdb/sirix-svelte-frontend/files/5320242/json-db.zip)

**Comment by mosheduminer** [comment]
This is with the consecutive diff branch, or the master branch? I know you're testing out the diff branch.

**Comment by JohannesLichtenberger** [comment]
It's the diff branch

**Comment by mosheduminer** [comment]
This is actually appears to be a server side bug. Running this in the pysirix shell: `diff -n 33 -s 1 -e 2` returns the diff, adding the depth parameter `diff -n 33 -s 1 -e 2 -d 3` returns an empty array.
Feel free to close this issue if I am correct.

**Comment by JohannesLichtenberger** [comment]
`-d 3` means you get the maximum depth, but the depth of the inserted fragment seems to be depth 6. Should be okay!?

**Comment by JohannesLichtenberger** [comment]
Ah, the maxDepth parameter until now didn't apply to the given root node, I just changed this. The other "bug" then is, that the depth count starts at 1 instead of 0, I guess :+1:
