### ISSUE TITLE
Settings page for lazy loading parameters on Firefox does not work

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix-svelte-frontend#272]
Firefox can't render the lazy loading input fields, it seems. Furthermore you can't close the window via the X.

**Comment by mosheduminer** [comment]
It sounds like there is an error causing the application to crash, which is why the window could not be closed afterward. This needs further investigation.

**Comment by mosheduminer** [comment]
I tested on firefox (on linux), and was unable to reproduce the problem. I am closing this issue, feel free to reopen if the issue persists.
