### ISSUE TITLE
To fetch new data, it seems that always two requests are sent

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix-svelte-frontend#273]
It might be okay, I'm just wondering why :)

**Comment by mosheduminer** [comment]
The first request is an `OPTIONS` and "preflight" request, used to check CORS permissions on the server. Any cross-domain request made in the browser will always be preceded by a preflight request. Is one of the two requests you see an OPTIONS request?

**Comment by JohannesLichtenberger** [comment]
No, both times a GET-request, both times serializing the resource

**Comment by mosheduminer** [comment]
Perhaps the server response is taking a long time, and to hovered twice over a node? There is no check (currently) preventing a double request in such a case.

**Comment by JohannesLichtenberger** [comment]
Is it only hovering? I though you'd have to explicitly click ;)

**Comment by mosheduminer** [comment]
I honestly don't remember. Need to check the code. I'll also check if I can reproduce the issue.

**Comment by mosheduminer** [comment]
This problem only appears on the initial resource load, and even then, it does not appear if the resource is refreshed by selecting the resource again.
